version: "2.1"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=iam,lambda,s3,sns,sqs,dynamodb
      - HOSTNAME_EXTERNAL=localstack
      - DEFAULT_REGION=eu-west-1
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-1
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  ls-api:
    network_mode: bridge
    build: like-stack-api/
    depends_on:
      - localstack
    links:
      - localstack
    ports:
      - 3005:3005
    volumes:
      - ./like-stack-api/:/app
      - /app/node_modules

  ls-client:
    network_mode: bridge
    build: like-stack-client/
    command: nodemon -L --exec "npm start" --watch app
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./like-stack-client/:/app-client
      - /app-client/node_modules
      - /usr/src/app/build
